# Generated by Django 5.0.1 on 2024-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="CourseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comprehension", models.TextField()),
                ("question", models.CharField(max_length=250)),
                ("examiner_answer", models.TextField()),
                ("student_answer", models.TextField()),
                ("student_score", models.IntegerField()),
                ("question_score", models.IntegerField()),
            ],
        ),
    ]
