# Generated by Django 5.0.2 on 2024-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultscore',
            name='percentage_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
