# Generated by Django 4.2.9 on 2024-01-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.coursequestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentscore',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
