# Generated by Django 4.2.9 on 2024-01-27 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0003_studentscore_question_studentscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestion',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentScore',
        ),
    ]
