# Generated by Django 5.0.2 on 2024-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examresultscore_percentage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
