# Generated by Django 4.2.9 on 2024-02-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequestion',
            name='question_id',
        ),
    ]
