# Generated by Django 5.0.2 on 2024-02-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_coursequestion_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.course'),
        ),
    ]
