# Generated by Django 5.0.2 on 2024-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestion',
            name='question_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
