# Generated by Django 4.2.9 on 2024-02-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0004_remove_coursequestion_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequestion',
            name='examiner',
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner', to=settings.AUTH_USER_MODEL),
        ),
    ]
