# Generated by Django 5.0.2 on 2024-02-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequestion',
            name='student',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='student_answer',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='student_score',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
