# Generated by Django 5.0.2 on 2024-02-17 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_coursequestion_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.course'),
        ),
    ]
