# Generated by Django 4.2.9 on 2024-01-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_coursequestion_examiner_alter_coursequestion_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequestion',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursequestion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursequestion',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursequestion',
            name='student_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
