# Generated by Django 5.0.2 on 2024-02-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequestion',
            name='exam',
        ),
    ]
