# Generated by Django 5.0.2 on 2024-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0006_examresultscore_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="similarity_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
