# Generated by Django 4.2.9 on 2024-02-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_coursequestion_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
