# Generated by Django 5.0.2 on 2024-02-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_examresult_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_score', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
        ),
    ]
